### ISSUE TITLE
where is the data folder

### ISSUE THREAD

**Issue by dingzw007** [shenqixiaojiang/APE-GAN#1]

**Comment by shenqixiaojiang** [comment]
@dingzw007  Hi, you should provide yours, including the path of adversarial examples and the path of clean examples.

**Comment by dingzhiwei007** [comment]
Hi,

Could you please provide an example? So that I can run your code successfully and know better about the format of the image files.

**Comment by shenqixiaojiang** [comment]
@dingzhiwei007  Hi !  Data has been uploaded. The data should be in the range [0,1] with the numpy data format.

**Comment by wycwycwyc** [comment]
你好，请问一下，我想用CIFAR10重新训练一个模型，那这两个cifarAdv.npy和cifarGt.npy怎么得到？
