### ISSUE TITLE
about the adversarial example generation algorithm

### ISSUE THREAD

**Issue by minfeixia** [shenqixiaojiang/APE-GAN#2]
Can I ask you which algorithm was used for the adversarial example of the MNIST dataset?

**Comment by shenqixiaojiang** [comment]
[FGSM](https://github.com/tensorflow/cleverhans/blob/master/cleverhans_tutorials/mnist_tutorial_tf.py) was used.

**Comment by minfeixia** [comment]
Then when I used the target model provided by cleverhans to classify adversarial examples in advData.npy, I discovered that the predicted classifications of the adversarial examples  were the correct classifications. I'm so confused about that.

**Comment by shenqixiaojiang** [comment]
是的，FGSM攻击算法产生的对抗样本不一定能实现对测试模型100%的分类错误率。
当eps＝0.3的时候还是有很高的错误率的，大概是可以实现90%的错误率。

**Comment by minfeixia** [comment]
非常同意您的看法，那么您advData.npy中的对抗样本的eps参数取的值是多大呢？是0.3吗？

**Comment by shenqixiaojiang** [comment]
@minfeixia 我在MNIST上用的是0.3，在CIFAR10上用的是0.1。
另外你还可以选择使用别的攻击算法产生的对抗样本作为训练集。这个不是必须FGSM算法产生的。
APE－GAN主要是提供了一种防御对抗样本的新思路。😄
