### ISSUE TITLE
关于.npy文件怎么得到

### ISSUE THREAD

**Issue by wycwycwyc** [shenqixiaojiang/APE-GAN#3]
你好，请问一下，我想用CIFAR10重新训练一个模型，那这两个cifarAdv.npy和cifarGt.npy文件怎么得到？

**Comment by shenqixiaojiang** [comment]
@wycwycwyc  Hi，cifarAdv.npy是生成的CIFAR10数据集上的对抗样本，你可以直接参考https://github.com/tensorflow/cleverhans 这个库。
论文中使用的是FGSM攻击算法生成的的对抗样本，具体而言就是使用 https://github.com/tensorflow/cleverhans/blob/master/cleverhans_tutorials/mnist_tutorial_tf.py  这个文件产生的，你将该文件产生的对抗样本保存成npy文件就好。

cifarGt.npy是你生成上面的对抗样本cifarAdv.npy使用的原始样本集。
